# This file autogenerated from gps_py.org

_ops_ = []

class Op:
    def __init__(self, action=[], preconds=[], add_list=[], del_list=[]):
        self.action = action
        self.preconds = preconds
        self.add_list = add_list
        self.del_list = del_list
    def __repr__(self):
        return str(vars(self))
